title: Dong Hu
markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Resume"
   link: "Dong Hu's CV.pdf"
 - name: "Contact"
   link: "contact"

remote_theme: ankitsultana/researcher@gem
